### ISSUE TITLE
OPENAI_API_KEY Error

### ISSUE THREAD

**Issue by CDProjects** [alexdphan/babyagi-chroma#1]
Hi, firstly thanks for this awesome project! I've run into an issue when trying to run babyagi - I've followed each 'How to Use' step to a t (except for the Optionals), I've both my OpenAI and Serpapi API keys saved as follows in my .env file, yet I continue to get the error below, when trying to run the program:

# API CONFIG
OPENAI_API_KEY=MYOPENAIAPIKEY
SERPAPI_API_KEY=MYSERPAPIAPIKEY

# TABLE CONFIG
TABLE_NAME=Storagi-table

# PROJECT CONFIG
OBJECTIVE=Write a weather report for SF today
FIRST_TASK=Develop a task list

```
C:\Baby-AGI\babyagi-chroma-agent>python babyagi-chroma.py
Traceback (most recent call last):
  File "C:\Baby-AGI\babyagi-chroma-agent\babyagi-chroma.py", line 25, in <module>
    assert OPENAI_API_KEY, "OPENAI_API_KEY environment variable is missing from .env"
AssertionError: OPENAI_API_KEY environment variable is missing from .env
```
I've no idea what I am doing wrong and I am quite noob when it comes to this sort of thing so my apologies if it's obvious what the issue is. I've my own OpenAI and SERPAPI API keys that I created just for this program.

Thank you in advance!

**Comment by alexdphan** [comment]
Hi @CDProjects! I can't replicate the environment you are having. Everything seems to work on my end when I followed the same steps. 

Have you tried replacing MYOPENAIAPIKEY with the actual API key? It should work after setting the .env vars.

Try `export OPENAI_API_KEY=your_api_key` in your terminal at the root of the project.

If all else doesn't work, feel free to provide more details and I'll see if there is something wrong here! :)

**Comment by CDProjects** [comment]
Thanks for taking a look @alexdphan - appreciate it.

Yep I have my own Open API key where I have pasted MYOPENAIAPIKEY, see below.

Thanks also for the tips - I had to set all of the variables in my terminal at the root of the project (Windows):

```
 C:\Baby-AGI\babyagi-chroma-agent>set OPENAI_API_KEY=sk-fWbikCZTbVOVdyVXXXXXXXXvTAFn8Vib5H1C02U3Cx

C:\Baby-AGI\babyagi-chroma-agent>python babyagi-chroma.py
Traceback (most recent call last):
  File "C:\Baby-AGI\babyagi-chroma-agent\babyagi-chroma.py", line 29, in <module>
    assert SERPAPI_API_KEY, "SERPAPI_API_KEY environment variable is missing from .env"
AssertionError: SERPAPI_API_KEY environment variable is missing from .env

C:\Baby-AGI\babyagi-chroma-agent>set SERPAPI_API_KEY=E724A3BB7XXXXXXXX318440032

C:\Baby-AGI\babyagi-chroma-agent>python babyagi-chroma.py
Traceback (most recent call last):
  File "C:\Baby-AGI\babyagi-chroma-agent\babyagi-chroma.py", line 34, in <module>
    assert YOUR_TABLE_NAME, "TABLE_NAME environment variable is missing from .env"
AssertionError: TABLE_NAME environment variable is missing from .env

C:\Baby-AGI\babyagi-chroma-agent>set TABLE_NAME=Storagi-table

C:\Baby-AGI\babyagi-chroma-agent>set OBJECTIVE=Write a weather report for SF today

C:\Baby-AGI\babyagi-chroma-agent>set FIRST_TASK=Develop a task list
```
I then ran `python babyagi-chroma.py` but then got the following error:

```
C:\Baby-AGI\babyagi-chroma-agent>python babyagi-chroma.py
Using embedded DuckDB with persistence: data will be stored in: chromadb
Traceback (most recent call last):
  File "C:\Baby-AGI\babyagi-chroma-agent\babyagi-chroma.py", line 55, in <module>
    vectorstore = Chroma(table_name, embeddings_model,
  File "C:\Program Files\Python310\lib\site-packages\langchain\vectorstores\chroma.py", line 85, in __init__
    self._collection = self._client.get_or_create_collection(
  File "C:\Program Files\Python310\lib\site-packages\chromadb\api\local.py", line 80, in get_or_create_collection
    return self.create_collection(name, metadata, embedding_function, get_or_create=True)
  File "C:\Program Files\Python310\lib\site-packages\chromadb\api\local.py", line 67, in create_collection
    check_index_name(name)
  File "C:\Program Files\Python310\lib\site-packages\chromadb\api\local.py", line 42, in check_index_name
    raise ValueError(msg)
ValueError: Expected collection name that (1) contains 3-63 characters, (2) starts and ends with an alphanumeric character, (3) otherwise contains only alphanumeric characters, underscores or hyphens (-), (4) contains no two consecutive periods (..) and (5) is not a valid IPv4 address, got Storagi-table

```
It seems there's an issue now with my `TABLE_NAME` which I'm not 100% sure about to be honest. I've tried changing it to '`Storagi`' and '`Storagi_table`' but to no avail. Many thanks in advance 🙏

**Comment by alexdphan** [comment]
I believe collections aren't created if they have a capital letter:

Seems like there is the collection name didn't meet formate requirements

refer here: https://discord.com/channels/1073293645303795742/1074711446589542552/1096107284746227814

**Comment by CDProjects** [comment]
Hey @alexdphan - my apologies for the late reply - everything is now in working order - thank you so much for your time and help! 🙏

**Comment by alexdphan** [comment]
Haha I assumed so! Happy to help :D
